-- Delete existing users to avoid conflicts
DELETE FROM users WHERE username IN ('admin', 'adminperidesk');

-- Check if admin user exists, if not create it
INSERT INTO users (username, password, first_name, last_name, role, is_active)
SELECT 'admin', '$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW', 'Admin', 'User', 'ADMIN', true
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin'); 

-- Motivational Quotes for PeriDesk Moderator Dashboard
INSERT INTO motivation_quotes (quote_text, author, category, is_active, created_at, updated_at)
VALUES
('Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'Albert Schweitzer', 'GENERAL', true, NOW(), NOW()),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'GENERAL', true, NOW(), NOW()),
('Opportunities don’t happen. You create them.', 'Chris Grosser', 'GENERAL', true, NOW(), NOW()),
('Don’t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'GENERAL', true, NOW(), NOW()),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'GENERAL', true, NOW(), NOW()),
('The harder you work for something, the greater you’ll feel when you achieve it.', 'Unknown', 'GENERAL', true, NOW(), NOW()),
('Dream bigger. Do bigger.', 'Unknown', 'GENERAL', true, NOW(), NOW()),
('Don’t stop when you’re tired. Stop when you’re done.', 'Marilyn Monroe', 'GENERAL', true, NOW(), NOW()),
('Wake up with determination. Go to bed with satisfaction.', 'George Lorimer', 'GENERAL', true, NOW(), NOW()),
('Do something today that your future self will thank you for.', 'Sean Patrick Flanery', 'GENERAL', true, NOW(), NOW()),
('Little things make big days.', 'Isabel Marant', 'GENERAL', true, NOW(), NOW()),
('It’s going to be hard, but hard does not mean impossible.', 'Art Williams', 'GENERAL', true, NOW(), NOW()),
('Push yourself, because no one else is going to do it for you.', 'Unknown', 'GENERAL', true, NOW(), NOW()),
('Great things never come from comfort zones.', 'Neil Strauss', 'GENERAL', true, NOW(), NOW()),
('Success doesn’t just find you. You have to go out and get it.', 'Unknown', 'GENERAL', true, NOW(), NOW()),
('The key to success is to focus our conscious mind on things we desire not things we fear.', 'Brian Tracy', 'GENERAL', true, NOW(), NOW()),
('Success is the sum of small efforts, repeated day in and day out.', 'Robert Collier', 'GENERAL', true, NOW(), NOW()),
('The secret of getting ahead is getting started.', 'Mark Twain', 'GENERAL', true, NOW(), NOW()),
('Quality is not an act, it is a habit.', 'Aristotle', 'GENERAL', true, NOW(), NOW()),
('The best way to predict the future is to create it.', 'Peter Drucker', 'GENERAL', true, NOW(), NOW()),
('Don’t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'GENERAL', true, NOW(), NOW()),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', 'GENERAL', true, NOW(), NOW()),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'GENERAL', true, NOW(), NOW()),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', 'GENERAL', true, NOW(), NOW()),
('The road to success and the road to failure are almost exactly the same.', 'Colin R. Davis', 'GENERAL', true, NOW(), NOW()),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'GENERAL', true, NOW(), NOW()),
('Success is not how high you have climbed, but how you make a positive difference to the world.', 'Roy T. Bennett', 'GENERAL', true, NOW(), NOW()),
('Try not to become a man of success. Rather become a man of value.', 'Albert Einstein', 'GENERAL', true, NOW(), NOW()),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'GENERAL', true, NOW(), NOW()),
('The future depends on what you do today.', 'Mahatma Gandhi', 'GENERAL', true, NOW(), NOW()),
('Don’t let yesterday take up too much of today.', 'Will Rogers', 'GENERAL', true, NOW(), NOW()),
('You don’t have to be great to start, but you have to start to be great.', 'Zig Ziglar', 'GENERAL', true, NOW(), NOW()),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'GENERAL', true, NOW(), NOW()),
('If you are not willing to risk the usual, you will have to settle for the ordinary.', 'Jim Rohn', 'GENERAL', true, NOW(), NOW()),
('Success is not final, failure is not fatal: It is the courage to continue that counts.', 'Winston Churchill', 'GENERAL', true, NOW(), NOW()),
('Success is not about how much money you make; it’s about the difference you make in people’s lives.', 'Michelle Obama', 'GENERAL', true, NOW(), NOW()),
('The only way to achieve the impossible is to believe it is possible.', 'Charles Kingsleigh', 'GENERAL', true, NOW(), NOW()),
('Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'Roy T. Bennett', 'GENERAL', true, NOW(), NOW()),
('Act as if what you do makes a difference. It does.', 'William James', 'GENERAL', true, NOW(), NOW()),
('What you get by achieving your goals is not as important as what you become by achieving your goals.', 'Zig Ziglar', 'GENERAL', true, NOW(), NOW()),
('The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it.', 'Jordan Belfort', 'GENERAL', true, NOW(), NOW()),
('If you want to achieve greatness stop asking for permission.', 'Unknown', 'GENERAL', true, NOW(), NOW()),
('The successful warrior is the average man, with laser-like focus.', 'Bruce Lee', 'GENERAL', true, NOW(), NOW()),
('Success is not for the chosen few, but for the few who choose it.', 'Unknown', 'GENERAL', true, NOW(), NOW()),
('Don’t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'GENERAL', true, NOW(), NOW()),
('The difference between ordinary and extraordinary is that little extra.', 'Jimmy Johnson', 'GENERAL', true, NOW(), NOW()),
('Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.', 'Orison Swett Marden', 'GENERAL', true, NOW(), NOW()),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'GENERAL', true, NOW(), NOW()),
('Success is liking yourself, liking what you do, and liking how you do it.', 'Maya Angelou', 'GENERAL', true, NOW(), NOW()),
('The secret of success is to do the common thing uncommonly well.', 'John D. Rockefeller Jr.', 'GENERAL', true, NOW(), NOW()),
('Success is not the absence of failure; it’s the persistence through failure.', 'Aisha Tyler', 'GENERAL', true, NOW(), NOW()),
('Success is not just making money. Success is happiness. Success is fulfillment; it’s the ability to give.', 'Adam Neumann', 'GENERAL', true, NOW(), NOW()),
('Success is not the result of spontaneous combustion. You must set yourself on fire.', 'Arnold H. Glasow', 'GENERAL', true, NOW(), NOW()),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'GENERAL', true, NOW(), NOW()),
('Success is not a destination, but the road that you’re on.', 'Marlon Wayans', 'GENERAL', true, NOW(), NOW()),
('Success is not the absence of problems, it’s the ability to deal with them.', 'Steve Maraboli', 'GENERAL', true, NOW(), NOW()),
('Success is not about being the best. It’s about always getting better.', 'Behance', 'GENERAL', true, NOW(), NOW()),
('Success is not a good teacher, failure makes you humble.', 'Shah Rukh Khan', 'GENERAL', true, NOW(), NOW()),
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer', 'GENERAL', true, NOW(), NOW()),
